AWSTemplateFormatVersion: 2010-09-09
Description: Parent stack for TodoApp two-tier (orchestrates Phase 1–4 as nested stacks)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for SSH (Bastion + Web)
  AdminIp:
    Type: String
    Description: Your public IPv4 /32 for SSH (e.g., 203.0.113.5/32)
    AllowedPattern: '^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/32$'
  DBUser:
    Type: String
    Default: admin
    Description: RDS master username
  DBPassword:
    Type: String
    NoEcho: true
    Description: RDS master password
  S3Bucket:
    Type: String
    Description: Bucket that holds Todo-Two-Tier.zip
  S3Key:
    Type: String
    Description: Key for Todo-Two-Tier.zip (e.g., Todo-Two-Tier.zip)
  VPCCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetACidr:
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnetACidr:
    Type: String
    Default: 10.0.2.0/24
  PublicSubnetBCidr:
    Type: String
    Default: 10.0.3.0/24
  PrivateSubnetBCidr:
    Type: String
    Default: 10.0.4.0/24

  # URLs to the child templates in S3
  Phase1TemplateUrl:
    Type: String
    Description: S3 URL to Phase 1 template
  Phase2TemplateUrl:
    Type: String
    Description: S3 URL to Phase 2 template
  Phase3TemplateUrl:
    Type: String
    Description: S3 URL to Phase 3 template
  Phase4TemplateUrl:
    Type: String
    Description: S3 URL to Phase 4 template

Resources:
  Phase1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref Phase1TemplateUrl
      Parameters:
        VPCCidr: !Ref VPCCidr
        PublicSubnetACidr: !Ref PublicSubnetACidr
        PrivateSubnetACidr: !Ref PrivateSubnetACidr
        PublicSubnetBCidr: !Ref PublicSubnetBCidr
        PrivateSubnetBCidr: !Ref PrivateSubnetBCidr

  Phase2:
    Type: AWS::CloudFormation::Stack
    DependsOn: Phase1
    Properties:
      TemplateURL: !Ref Phase2TemplateUrl
      Parameters:
        AdminIp: !Ref AdminIp

  Phase3:
    Type: AWS::CloudFormation::Stack
    DependsOn: Phase2
    Properties:
      TemplateURL: !Ref Phase3TemplateUrl
      Parameters:
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        KeyName: !Ref KeyName

  Phase4:
    Type: AWS::CloudFormation::Stack
    DependsOn: Phase3
    Properties:
      TemplateURL: !Ref Phase4TemplateUrl
      Parameters:
        KeyName: !Ref KeyName
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword

Outputs:
  ALBDNSName:
    Description: ALB DNS from Phase 4
    Value: !GetAtt Phase4.Outputs.ALBDNSName
